ERROR 2024-03-31 16:43:40,225 views 10272 14544 Failed to create a new user: {'username': [ErrorDetail(string='A user with that username already exists.', code='unique')]}
WARNING 2024-03-31 16:43:40,226 log 10272 14544 Bad Request: /auth/sign-up/
WARNING 2024-03-31 16:43:40,226 basehttp 10272 14544 "POST /auth/sign-up/ HTTP/1.1" 400 58
WARNING 2024-03-31 16:56:31,284 log 8944 11740 Unauthorized: /auth/sign-in/
WARNING 2024-03-31 16:56:31,284 basehttp 8944 11740 "POST /auth/sign-in/ HTTP/1.1" 401 63
WARNING 2024-03-31 16:56:41,623 log 8944 11740 Unauthorized: /api/token/
WARNING 2024-03-31 16:56:41,623 basehttp 8944 11740 "POST /api/token/ HTTP/1.1" 401 63
ERROR 2024-03-31 16:56:51,481 views 8944 11740 Failed to create a new user: {'username': [ErrorDetail(string='A user with that username already exists.', code='unique')]}
WARNING 2024-03-31 16:56:51,481 log 8944 11740 Bad Request: /auth/sign-up/
WARNING 2024-03-31 16:56:51,482 basehttp 8944 11740 "POST /auth/sign-up/ HTTP/1.1" 400 58
WARNING 2024-03-31 16:57:15,494 log 8944 11740 Unauthorized: /auth/sign-in/
WARNING 2024-03-31 16:57:15,494 basehttp 8944 11740 "POST /auth/sign-in/ HTTP/1.1" 401 63
WARNING 2024-03-31 16:59:05,541 log 14204 5208 Unauthorized: /auth/sign-in/
WARNING 2024-03-31 16:59:05,542 basehttp 14204 5208 "POST /auth/sign-in/ HTTP/1.1" 401 63
WARNING 2024-03-31 16:59:22,756 log 14204 5208 Unauthorized: /auth/sign-in/
WARNING 2024-03-31 16:59:22,756 basehttp 14204 5208 "POST /auth/sign-in/ HTTP/1.1" 401 63
WARNING 2024-03-31 17:01:38,174 log 14204 13368 Unauthorized: /auth/sign-in/
WARNING 2024-03-31 17:01:38,175 basehttp 14204 13368 "POST /auth/sign-in/ HTTP/1.1" 401 63
WARNING 2024-03-31 17:02:05,180 log 14204 13368 Unauthorized: /auth/sign-in/
WARNING 2024-03-31 17:02:05,180 basehttp 14204 13368 "POST /auth/sign-in/ HTTP/1.1" 401 63
WARNING 2024-03-31 17:56:09,270 log 6512 9800 Unauthorized: /auth/sign-in/
WARNING 2024-03-31 17:56:09,270 basehttp 6512 9800 "POST /auth/sign-in/ HTTP/1.1" 401 63
WARNING 2024-03-31 18:07:21,639 log 12744 5452 Unauthorized: /auth/sign-in/
WARNING 2024-03-31 18:07:21,640 basehttp 12744 5452 "POST /auth/sign-in/ HTTP/1.1" 401 63
WARNING 2024-03-31 18:10:03,457 log 11192 6492 Unauthorized: /auth/sign-in/two
WARNING 2024-03-31 18:10:03,457 basehttp 11192 6492 "POST /auth/sign-in/two HTTP/1.1" 401 63
ERROR 2024-03-31 18:12:32,706 log 13080 11724 Internal Server Error: /auth/sign-up/
Traceback (most recent call last):
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.UniqueViolation: ОШИБКА:  повторяющееся значение ключа нарушает ограничение уникальности "auth_user_username_key"
DETAIL:  Ключ "(username)=(testing_project)" уже существует.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\ToDoMany\ToDoSource\api\views.py", line 43, in create_user
    UserProfile.objects.create_user(**data)
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\django\contrib\auth\models.py", line 161, in create_user
    return self._create_user(username, email, password, **extra_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\django\contrib\auth\models.py", line 155, in _create_user
    user.save(using=self._db)
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\django\contrib\auth\base_user.py", line 78, in save
    super().save(*args, **kwargs)
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\django\db\models\base.py", line 822, in save
    self.save_base(
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\django\db\models\base.py", line 906, in save_base
    parent_inserted = self._save_parents(
                      ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\django\db\models\base.py", line 959, in _save_parents
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\django\db\models\base.py", line 1067, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\django\db\models\base.py", line 1108, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\django\db\models\query.py", line 1847, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1823, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: ОШИБКА:  повторяющееся значение ключа нарушает ограничение уникальности "auth_user_username_key"
DETAIL:  Ключ "(username)=(testing_project)" уже существует.

ERROR 2024-03-31 18:12:32,712 basehttp 13080 11724 "POST /auth/sign-up/ HTTP/1.1" 500 199034
WARNING 2024-03-31 18:13:18,803 log 13080 11724 Unauthorized: /auth/sign-in/
WARNING 2024-03-31 18:13:18,804 basehttp 13080 11724 "POST /auth/sign-in/ HTTP/1.1" 401 63
WARNING 2024-03-31 18:14:46,895 log 1332 12844 Unauthorized: /auth/sign-in/
WARNING 2024-03-31 18:14:46,896 basehttp 1332 12844 "POST /auth/sign-in/ HTTP/1.1" 401 63
WARNING 2024-03-31 18:15:48,658 log 12492 12204 Bad Request: /auth/sign-up/
WARNING 2024-03-31 18:15:48,658 basehttp 12492 12204 "POST /auth/sign-up/ HTTP/1.1" 400 58
WARNING 2024-04-01 15:16:11,002 log 15828 8196 Not Found: /favicon.ico
WARNING 2024-04-01 15:16:48,469 log 15828 11704 Unauthorized: /demo/api/environment/
WARNING 2024-04-01 15:16:48,470 basehttp 15828 11704 "GET /demo/api/environment/ HTTP/1.1" 401 58
WARNING 2024-04-01 15:19:45,875 log 5904 17148 Unauthorized: /auth/sign-in/
WARNING 2024-04-01 15:19:45,876 basehttp 5904 17148 "POST /auth/sign-in/ HTTP/1.1" 401 63
WARNING 2024-04-01 15:20:12,687 log 5904 17148 Bad Request: /auth/sign-up/
WARNING 2024-04-01 15:20:12,687 basehttp 5904 17148 "POST /auth/sign-up/ HTTP/1.1" 400 58
ERROR 2024-04-01 15:21:37,155 log 14204 4136 Internal Server Error: /demo/api/environment/
Traceback (most recent call last):
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.UndefinedColumn: ОШИБКА:  столбец ToDoSource_environment.password не существует
LINE 1: ...vironment"."id", "ToDoSource_environment"."name", "ToDoSourc...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\ToDoMany\ToDoSource\api\views.py", line 240, in get
    return Response(serializer.data, status=status.HTTP_200_OK)
                    ^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\rest_framework\serializers.py", line 795, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\rest_framework\serializers.py", line 249, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\rest_framework\serializers.py", line 713, in to_representation
    return [
           ^
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\django\db\models\query.py", line 400, in __iter__
    self._fetch_all()
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.ProgrammingError: ОШИБКА:  столбец ToDoSource_environment.password не существует
LINE 1: ...vironment"."id", "ToDoSource_environment"."name", "ToDoSourc...
                                                             ^

ERROR 2024-04-01 15:21:37,160 basehttp 14204 4136 "GET /demo/api/environment/ HTTP/1.1" 500 25330
ERROR 2024-04-01 15:26:21,732 log 2976 14644 Internal Server Error: /swagger/
Traceback (most recent call last):
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\drf_yasg\views.py", line 96, in get
    schema = generator.get_schema(request, self.public)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\drf_yasg\generators.py", line 276, in get_schema
    paths, prefix = self.get_paths(endpoints, components, request, public)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\drf_yasg\generators.py", line 482, in get_paths
    operation = self.get_operation(view, path, prefix, method, components, request)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\drf_yasg\generators.py", line 524, in get_operation
    operation = view_inspector.get_operation(operation_keys)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\drf_yasg\inspectors\view.py", line 45, in get_operation
    responses = self.get_responses()
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\drf_yasg\inspectors\view.py", line 182, in get_responses
    responses=self.get_response_schemas(response_serializers)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\drf_yasg\inspectors\view.py", line 271, in get_response_schemas
    schema=self.serializer_to_schema(serializer),
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\drf_yasg\inspectors\base.py", line 438, in serializer_to_schema
    return self.probe_inspectors(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\drf_yasg\inspectors\base.py", line 110, in probe_inspectors
    result = method(obj, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\drf_yasg\inspectors\field.py", line 38, in get_schema
    return self.probe_field_inspectors(serializer, openapi.Schema, self.use_definitions)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\drf_yasg\inspectors\base.py", line 228, in probe_field_inspectors
    return self.probe_inspectors(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\drf_yasg\inspectors\base.py", line 110, in probe_inspectors
    result = method(obj, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\drf_yasg\inspectors\field.py", line 82, in field_to_swagger_object
    child_schema = self.probe_field_inspectors(field.child, ChildSwaggerType, use_references)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\drf_yasg\inspectors\base.py", line 228, in probe_field_inspectors
    return self.probe_inspectors(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\drf_yasg\inspectors\base.py", line 110, in probe_inspectors
    result = method(obj, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\drf_yasg\inspectors\field.py", line 129, in field_to_swagger_object
    actual_schema = definitions.setdefault(ref_name, make_schema_definition)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\drf_yasg\openapi.py", line 685, in setdefault
    ret = maker()
          ^^^^^^^
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\drf_yasg\inspectors\field.py", line 98, in make_schema_definition
    for property_name, child in serializer.fields.items():
                                ^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\rest_framework\serializers.py", line 372, in fields
    for key, value in self.get_fields().items():
                      ^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\rest_framework\serializers.py", line 1079, in get_fields
    field_names = self.get_field_names(declared_fields, info)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\rest_framework\serializers.py", line 1144, in get_field_names
    assert not (fields and exclude), (
AssertionError: Cannot set both 'fields' and 'exclude' options on serializer EnvironmentSerializer.
ERROR 2024-04-01 15:26:21,737 basehttp 2976 14644 "GET /swagger/?format=openapi HTTP/1.1" 500 236452
ERROR 2024-04-01 15:29:46,245 log 13628 16760 Internal Server Error: /swagger/
Traceback (most recent call last):
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\drf_yasg\views.py", line 96, in get
    schema = generator.get_schema(request, self.public)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\drf_yasg\generators.py", line 276, in get_schema
    paths, prefix = self.get_paths(endpoints, components, request, public)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\drf_yasg\generators.py", line 482, in get_paths
    operation = self.get_operation(view, path, prefix, method, components, request)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\drf_yasg\generators.py", line 524, in get_operation
    operation = view_inspector.get_operation(operation_keys)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\drf_yasg\inspectors\view.py", line 45, in get_operation
    responses = self.get_responses()
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\drf_yasg\inspectors\view.py", line 182, in get_responses
    responses=self.get_response_schemas(response_serializers)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\drf_yasg\inspectors\view.py", line 271, in get_response_schemas
    schema=self.serializer_to_schema(serializer),
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\drf_yasg\inspectors\base.py", line 438, in serializer_to_schema
    return self.probe_inspectors(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\drf_yasg\inspectors\base.py", line 110, in probe_inspectors
    result = method(obj, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\drf_yasg\inspectors\field.py", line 38, in get_schema
    return self.probe_field_inspectors(serializer, openapi.Schema, self.use_definitions)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\drf_yasg\inspectors\base.py", line 228, in probe_field_inspectors
    return self.probe_inspectors(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\drf_yasg\inspectors\base.py", line 110, in probe_inspectors
    result = method(obj, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\drf_yasg\inspectors\field.py", line 82, in field_to_swagger_object
    child_schema = self.probe_field_inspectors(field.child, ChildSwaggerType, use_references)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\drf_yasg\inspectors\base.py", line 228, in probe_field_inspectors
    return self.probe_inspectors(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\drf_yasg\inspectors\base.py", line 110, in probe_inspectors
    result = method(obj, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\drf_yasg\inspectors\field.py", line 129, in field_to_swagger_object
    actual_schema = definitions.setdefault(ref_name, make_schema_definition)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\drf_yasg\openapi.py", line 685, in setdefault
    ret = maker()
          ^^^^^^^
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\drf_yasg\inspectors\field.py", line 98, in make_schema_definition
    for property_name, child in serializer.fields.items():
                                ^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\rest_framework\serializers.py", line 372, in fields
    for key, value in self.get_fields().items():
                      ^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\rest_framework\serializers.py", line 1079, in get_fields
    field_names = self.get_field_names(declared_fields, info)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\rest_framework\serializers.py", line 1191, in get_field_names
    assert field_name not in self._declared_fields, (
AssertionError: Cannot both declare the field 'user' and include it in the EnvironmentSerializer 'exclude' option. Remove the field or, if inherited from a parent serializer, disable with `user = None`.
ERROR 2024-04-01 15:29:46,250 basehttp 13628 16760 "GET /swagger/?format=openapi HTTP/1.1" 500 239542
ERROR 2024-04-01 15:31:16,124 log 7684 15708 Internal Server Error: /swagger/
Traceback (most recent call last):
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\drf_yasg\views.py", line 96, in get
    schema = generator.get_schema(request, self.public)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\drf_yasg\generators.py", line 276, in get_schema
    paths, prefix = self.get_paths(endpoints, components, request, public)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\drf_yasg\generators.py", line 482, in get_paths
    operation = self.get_operation(view, path, prefix, method, components, request)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\drf_yasg\generators.py", line 524, in get_operation
    operation = view_inspector.get_operation(operation_keys)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\drf_yasg\inspectors\view.py", line 45, in get_operation
    responses = self.get_responses()
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\drf_yasg\inspectors\view.py", line 182, in get_responses
    responses=self.get_response_schemas(response_serializers)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\drf_yasg\inspectors\view.py", line 271, in get_response_schemas
    schema=self.serializer_to_schema(serializer),
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\drf_yasg\inspectors\base.py", line 438, in serializer_to_schema
    return self.probe_inspectors(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\drf_yasg\inspectors\base.py", line 110, in probe_inspectors
    result = method(obj, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\drf_yasg\inspectors\field.py", line 38, in get_schema
    return self.probe_field_inspectors(serializer, openapi.Schema, self.use_definitions)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\drf_yasg\inspectors\base.py", line 228, in probe_field_inspectors
    return self.probe_inspectors(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\drf_yasg\inspectors\base.py", line 110, in probe_inspectors
    result = method(obj, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\drf_yasg\inspectors\field.py", line 82, in field_to_swagger_object
    child_schema = self.probe_field_inspectors(field.child, ChildSwaggerType, use_references)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\drf_yasg\inspectors\base.py", line 228, in probe_field_inspectors
    return self.probe_inspectors(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\drf_yasg\inspectors\base.py", line 110, in probe_inspectors
    result = method(obj, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\drf_yasg\inspectors\field.py", line 129, in field_to_swagger_object
    actual_schema = definitions.setdefault(ref_name, make_schema_definition)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\drf_yasg\openapi.py", line 685, in setdefault
    ret = maker()
          ^^^^^^^
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\drf_yasg\inspectors\field.py", line 98, in make_schema_definition
    for property_name, child in serializer.fields.items():
                                ^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\rest_framework\serializers.py", line 372, in fields
    for key, value in self.get_fields().items():
                      ^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\rest_framework\serializers.py", line 1079, in get_fields
    field_names = self.get_field_names(declared_fields, info)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\rest_framework\serializers.py", line 1191, in get_field_names
    assert field_name not in self._declared_fields, (
AssertionError: Cannot both declare the field 'user' and include it in the EnvironmentSerializer 'exclude' option. Remove the field or, if inherited from a parent serializer, disable with `user = None`.
ERROR 2024-04-01 15:31:16,130 basehttp 7684 15708 "GET /swagger/?format=openapi HTTP/1.1" 500 239508
WARNING 2024-04-01 15:42:31,274 log 15428 13688 Bad Request: /demo/api/tasks/
WARNING 2024-04-01 15:42:31,275 basehttp 15428 13688 "POST /demo/api/tasks/ HTTP/1.1" 400 61
WARNING 2024-04-01 15:42:37,127 log 15428 13688 Bad Request: /demo/api/tasks/
WARNING 2024-04-01 15:42:37,128 basehttp 15428 13688 "POST /demo/api/tasks/ HTTP/1.1" 400 61
WARNING 2024-04-01 15:50:34,518 log 14816 3044 Unauthorized: /demo/api/tasks/
WARNING 2024-04-01 15:50:34,518 basehttp 14816 3044 "POST /demo/api/tasks/ HTTP/1.1" 401 58
ERROR 2024-04-01 15:54:22,137 log 3564 8584 Internal Server Error: /demo/api/tasks/for_environment/1/
Traceback (most recent call last):
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\rest_framework\views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\ToDoMany\venv\Lib\site-packages\rest_framework\views.py", line 423, in finalize_response
    assert isinstance(response, HttpResponseBase), (
AssertionError: Expected a `Response`, `HttpResponse` or `StreamingHttpResponse` to be returned from the view, but received a `<class 'NoneType'>`
ERROR 2024-04-01 15:54:22,139 basehttp 3564 8584 "POST /demo/api/tasks/for_environment/1/ HTTP/1.1" 500 21729
